name: HW15 Tests workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest
    container:
      image: centos:8

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Update yum repos
      run: |
        sed -i s/mirror.centos.org/vault.centos.org/g /etc/yum.repos.d/CentOS-*.repo
        sed -i s/^#.*baseurl=http/baseurl=http/g /etc/yum.repos.d/CentOS-*.repo
        sed -i s/^mirrorlist=http/#mirrorlist=http/g /etc/yum.repos.d/CentOS-*.repo

    - name: Install dependencies
      run: |
        yum install -y gcc make protobuf protobuf-c protobuf-c-compiler protobuf-c-devel python38-devel python3-setuptools gdb zlib-devel

    - name: Set ulimit
      run: ulimit -c unlimited

    - name: Create necessary directory
      run: |
        mkdir -p /tmp/otus
        mkdir -p /tmp/otus/tests

    - name: Copy necessary files
      run: |
        cp ./homework_15/deviceapps.proto /tmp/otus/
        cp ./homework_15/setup.py /tmp/otus/
        cp ./homework_15/pb.c /tmp/otus/
        cp ./homework_15/start.sh /tmp/otus/
        cp ./homework_15/tests/__init__.py /tmp/otus/tests/
        cp ./homework_15/tests/test_pb.py /tmp/otus/tests/
      
    - name: Compile protobuf
      run: |
        cd /tmp/otus
        protoc-c --c_out=. deviceapps.proto
        protoc -I . --python_out=. deviceapps.proto

    - name: List files in /tmp/otus
      run: |
        ls -la /tmp/otus
        ls -la /tmp/otus/tests
        
    - name: Create venv
      run: |
        cd /tmp/otus
        python3 -m venv venv
        source venv/bin/activate
        python3 -m pip install protobuf==3.20.*
    
    - name: Run tests
      run: |
        cd /tmp/otus
        python3.8 setup.py test
